### PR TITLE
📈 Add JaCoCo and upload coverage reports to Codecov

### LINKED ISSUE #59: 📈 Create code coverage reports with JaCoCo and publish code coverage reports to Codecov
It will help us to see which parts are untested and will allows us to add another beautiful status badge 😁.

### PR DESCRIPTION
**Pull request by helpermethod**
Fixes #59.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hum, hum, got to admit I'm not super-convinced of this one. We hardly have any tests at this point, so the report would be mostly noise on PRs. Also I'm personally not the strongest believer in monitoring test coverage to begin with. So I think I'm -0 on this change.

@SiddiqueAhmad, @karim-elngr, as you were discussing testing via Testcontainers, what's your take on this? Yay or nay?

**Comment by helpermethod** [comment]
Yes, it may be too early at this point. And on its own it's a useless metric, but I've found it helpful to gain a good understanding which parts of the code may need additional testing.

Maybe my fist goal should be to add some useful tests :).

**Comment by SiddiqueAhmad** [comment]
nay :)

**Comment by helpermethod** [comment]
Closing the issue for now.

**Pull request closed without merging**
