### PR TITLE
chore: Split changelog entries by dependencies and other changes

### PR DESCRIPTION
**Pull request by helpermethod**
See #285 for more context. Splits changes into dependabot related dependencies and other changes.

### CODE REVIEW

**Comment by aalmiray** [comment]
LGTM

**Review by gunnarmorling — APPROVED** [review]
Thx, @helpermethod! How about other changes, not done by dependabot? Will they be categorised in the same way as before?

**Comment by helpermethod** [comment]
> Thx, @helpermethod! How about other changes, not done by dependabot? Will they be categorised in the same way as before?

Hi @gunnarmorling. It will put them at the top into the category `Changes`. Other than that, nothing changes.

**Review by gunnarmorling — APPROVED** [review]

**Comment by gunnarmorling** [comment]
Excellent, thank you so much!

**Pull request merged**
