### PR TITLE
💥 Use a property as conditional for the filename extension.

### PR DESCRIPTION
**Pull request by michael-simons**
As @aalmiray said here https://andresalmiray.com/crafting-rolling-releases-for-a-quarkus-cli-application/

> Notice that the only difference between them is the use of the .exe file extension for the executable files. If someone knows a shorter, more concise version to get the job done please do let me know!

This is the notice. :)

### CODE REVIEW

**Comment by gunnarmorling** [comment]
LGTM, very nice ratio of added vs. removed lines :) Thanks a lot @michael-simons 🙏 ! Any concerns by our build grand master @aalmiray?

**Comment by aalmiray** [comment]
LGTM as well ✨

**Comment by gunnarmorling** [comment]
And applied. Thx, @michael-simons!

**Comment by michael-simons** [comment]
Very welcome, @gunnarmorling ! I hope this is not related: https://github.com/kcctl/kcctl/runs/3184534695#step:6:12 though.

**Comment by aalmiray** [comment]
@michael-simons no, it's unrelated. JReleaser had a hiccup with its latest early-access release. Just kicked it.

**Pull request merged**
